"""Predefined judge-ready scenarios with transparent assumptions."""

from __future__ import annotations

from src.models.scenario import ScenarioDefinition


SCENARIOS: dict[str, ScenarioDefinition] = {
    "moderate_storage": ScenarioDefinition(
        scenario_id="moderate_storage",
        name="Moderate rain + storage available",
        description="A partly empty tank safely captures a moderate event.",
        rainfall_mm=8.0,
        rainfall_intensity_mm_hr=16.0,
        catchment_area_m2=1_200.0,
        runoff_coefficient=0.72,
        storage_capacity_l=18_000.0,
        current_storage_l=5_000.0,
        recharge_capacity_l_per_hour=1_500.0,
        recharge_available=True,
        soil_saturation_percent=35.0,
        drain_stress_percent=55.0,
        turbidity_ntu=3.0,
        ph=7.2,
        expected_tendency="STORE",
    ),
    "heavy_recharge": ScenarioDefinition(
        scenario_id="heavy_recharge",
        name="Heavy rain + tank nearly full + recharge available",
        description="Tank headroom is scarce, so safe water also uses recharge capacity.",
        rainfall_mm=25.0,
        rainfall_intensity_mm_hr=65.0,
        catchment_area_m2=2_000.0,
        runoff_coefficient=0.82,
        storage_capacity_l=25_000.0,
        current_storage_l=22_000.0,
        recharge_capacity_l_per_hour=22_000.0,
        recharge_available=True,
        soil_saturation_percent=28.0,
        drain_stress_percent=82.0,
        turbidity_ntu=2.8,
        ph=7.1,
        expected_tendency="RECHARGE / STORE_AND_RECHARGE",
    ),
    "contaminated_first_flush": ScenarioDefinition(
        scenario_id="contaminated_first_flush",
        name="Heavy rain + contaminated first flush",
        description="The safety gate overrides retention objectives.",
        rainfall_mm=14.0,
        rainfall_intensity_mm_hr=55.0,
        catchment_area_m2=1_500.0,
        runoff_coefficient=0.85,
        storage_capacity_l=20_000.0,
        current_storage_l=4_000.0,
        recharge_capacity_l_per_hour=8_000.0,
        recharge_available=True,
        soil_saturation_percent=30.0,
        drain_stress_percent=78.0,
        turbidity_ntu=58.0,
        ph=6.1,
        contamination_detected=True,
        first_flush_active=True,
        expected_tendency="DIVERT / BLOCK RECHARGE",
    ),
    "extreme_capacity_exhausted": ScenarioDefinition(
        scenario_id="extreme_capacity_exhausted",
        name="Extreme rain + storage full + soil saturated",
        description="Distributed nodes have finite capacity; residual flow is discharged.",
        rainfall_mm=42.0,
        rainfall_intensity_mm_hr=120.0,
        catchment_area_m2=2_400.0,
        runoff_coefficient=0.90,
        storage_capacity_l=30_000.0,
        current_storage_l=30_000.0,
        recharge_capacity_l_per_hour=18_000.0,
        recharge_available=True,
        soil_saturation_percent=94.0,
        drain_stress_percent=96.0,
        turbidity_ntu=3.2,
        ph=7.0,
        expected_tendency="CONTROLLED_DISCHARGE",
    ),
    "multi_retention": ScenarioDefinition(
        scenario_id="multi_retention",
        name="Heavy rain + high drain stress + multiple retention options",
        description="Storage and eligible recharge operate together before discharge.",
        rainfall_mm=20.0,
        rainfall_intensity_mm_hr=70.0,
        catchment_area_m2=1_800.0,
        runoff_coefficient=0.78,
        storage_capacity_l=28_000.0,
        current_storage_l=16_000.0,
        recharge_capacity_l_per_hour=12_000.0,
        recharge_available=True,
        soil_saturation_percent=38.0,
        drain_stress_percent=91.0,
        turbidity_ntu=3.5,
        ph=7.4,
        expected_tendency="OPTIMIZE RETENTION",
    ),
    "dry_readiness": ScenarioDefinition(
        scenario_id="dry_readiness",
        name="Dry conditions",
        description="Retained-water inventory and next-event capacity are visible.",
        rainfall_mm=0.0,
        rainfall_intensity_mm_hr=0.0,
        catchment_area_m2=1_500.0,
        runoff_coefficient=0.75,
        storage_capacity_l=22_000.0,
        current_storage_l=9_000.0,
        recharge_capacity_l_per_hour=5_000.0,
        recharge_available=True,
        soil_saturation_percent=22.0,
        drain_stress_percent=12.0,
        turbidity_ntu=2.5,
        ph=7.2,
        expected_tendency="READINESS / HOLD INVENTORY",
    ),
}


def get_scenario(scenario_id: str) -> ScenarioDefinition:
    try:
        return SCENARIOS[scenario_id]
    except KeyError as exc:
        raise KeyError(f"Unknown scenario: {scenario_id}") from exc

